### ISSUE TITLE
About the implementation of FedDyn

### ISSUE THREAD

**Issue by superjdz** [woodenchild95/FL-Simulator#14]
It might be hard to understand why the second part of loss computed in the code is correspondding to the last two terms in the algorithm of the fedDyn paper ?
![image](https://github.com/user-attachments/assets/29cb43cc-2388-4eb3-9b90-7405523470e6)
![image](https://github.com/user-attachments/assets/e197971f-323b-4e0a-8643-1e4fd2d19c9d)

**Comment by woodenchild95** [comment]
@superjdz This form is equivalent to the SGD solution for the original problem. You may attempt to derive the gradient form of the entire loss function and compare it. Alternatively, you can modify it into a form you are more familiar with. The final result will not differ significantly. If you are referring to the gradient of the quadratic term, it can be expanded through vector multiplication into an l2 regularization term and a difference term. The gradient form of the section you highlighted is split into two losses: one is the local_dual_correction term, and the other is embedded in the weight_decay. You can observe their connection by simplifying the gradients of all the losses.

**Comment by superjdz** [comment]
Thank you for your explanation! I see their graidients are roughly the same. And i will close this issue.
